language: php

php:
  - 5.6
  - 7.0
  - 7.1
  - nightly

matrix:
  fast_finish: true

  allow_failures:
    - php: nightly

cache:
  directories:
    - $HOME/.composer/cache

services:
  - sqlite

before_script:
  - composer install
  - travis_retry composer self-update
  - travis_retry composer update ${COMPOSER_FLAGS} --no-interaction --prefer-dist

script:
  - vendor/bin/phpunit --debug --disable-coverage-ignore --verbose --colors=always --no-extensions --stop-on-error --stop-on-failure --stop-on-warning  --stop-on-risky --stop-on-skipped --stop-on-incomplete --fail-on-warning --fail-on-risky
